k8s_config:
- manifest_path: /manifests
  cluster_info:
    cluster_id: 7c93ee61-4bd3-5686-a7ab-193ee970021a
    cluster_name: Alex's cluster
- manifest_path: /manifests
  cluster_info:
    cluster_id: bcd6ec1a-6e7e-5bf9-98f6-ac94097a1d01
    cluster_name: Alex Gervais's cluster
- manifest_path: /manifests
  cluster_info:
    cluster_id: 896689dd-3ad1-5446-9f88-0b615dc56c29
    cluster_name: Alex Gervais's cluster
