---
apiVersion: v1
kind: Service
metadata:
  name: quote
  namespace: gitops-demo
  annotations:
    a8r.io/description: "Quote of the Moment"
    a8r.io/owner: "alexgervais"
    a8r.io/chat: "#emissary"
    a8r.io/documentation: "https://github.com/datawire/qotm/blob/master/README.md"
    a8r.io/repository: "https://github.com/datawire/qotm"
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: quote
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
  namespace: gitops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: quote
    spec:
      containers:
      - name: backend
        image: quay.io/datawire/quote:0.3.0
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
