apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quote
  namespace: argocd
spec:
  destination:
    namespace: gitops-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/
    repoURL: https://github.com/alexgervais/a8r-gitops-example.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}